### ISSUE TITLE
UNeuronLiveLinkBPLibrary::GetNeuronFrameInUE4  Can you explain this Api?

### ISSUE THREAD

**Issue by meluoluo** [pnmocap/NoitomMocapLiveLinkPlugin#4]
I through UNeuronLiveLinkBPLibrary: : GetNeuronFrameInUE4 (const FName & AvatarName, bool & WithDisplacement, TArray < FName > &  BoneNames,TArray<FVector>& Locations,TArray<FQuat>& Rotations) interface to store real-time capture data, and then through the custom method to read the stored data, directly set the data to the corresponding Bone.  But the effect of driving is not ideal .Can't the values from this API be applied directly to Bone?

DriveMode:

FCompactPoseBoneIndex CPIndex = Container.MakeCompactPoseIndex(FMeshPoseBoneIndex(MeshBoneIndex));
						FTransform CSTransformFromSource = OutPutCsPose.GetComponentSpaceTransform(CPIndex);//
						FTransform comptransform = Output.AnimInstanceProxy->GetComponentTransform();
						FAnimationRuntime::ConvertCSTransformToBoneSpace(comptransform, OutPutCsPose, CSTransformFromSource, CPIndex, EBoneControlSpace::BCS_BoneSpace);
						
						//Get the corresponding rotation of Bone in the stored data and set
						CSTransformFromSource.SetRotation(NeuronBonesComponentSpaceRotation[i]);

						FAnimationRuntime::ConvertBoneSpaceTransformToCS(comptransform, OutPutCsPose, CSTransformFromSource, CPIndex, EBoneControlSpace::BCS_BoneSpace);
						if (CPIndex != INDEX_NONE)
						{
							OutPutCsPose.SetComponentSpaceTransform(CPIndex, CSTransformFromSource);
							FCSPose<FCompactPose>::ConvertComponentPosesToLocalPoses(OutPutCsPose, Output.Pose);
						}

**Comment by lijinlong** [comment]
You can check the code in UNeuronLiveLinkRemapAsset::BuildPoseFromAnimationData to see how to use the output data in UNeuronLiveLinkBPLibrary: : GetNeuronFrameInUE4. the output data is stored in const FLiveLinkAnimationFrameData struct
