### ISSUE TITLE
5.1

### ISSUE THREAD

**Issue by MRZHL** [pnmocap/NoitomMocapLiveLinkPlugin#7]
使用5.1 的 版本 驱动 metahuman 按照 Bilibili 上的教程，双手，和 双肩有问题。
<img width="1051" alt="a239aa7305fbe4f3bbaade40c6e233c" src="https://user-images.githubusercontent.com/16567680/229336606-29a4647e-dbe3-477a-aece-347f4fdf383b.png">
<img width="384" alt="954cb2126631b339ee47fa4cc518bba" src="https://user-images.githubusercontent.com/16567680/229336612-02f6183f-df8e-4d4c-b7e6-4489f75caee2.png">

**Comment by lijinlong** [comment]
已修改,请使用v1.3.1版插件
